/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ogn_messages.proto */

#ifndef PROTOBUF_C_ogn_5fmessages_2eproto__INCLUDED
#define PROTOBUF_C_ogn_5fmessages_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Terminator12__Ogn__PositionReport Terminator12__Ogn__PositionReport;


/* --- enums --- */


/* --- messages --- */

/*
 * One APRS position report, decoded into structured fields by the worker thread
 * and shipped over a named FIFO (see config/ogn_config.h) to the renderer.
 */
struct  Terminator12__Ogn__PositionReport
{
  ProtobufCMessage base;
  char *callsign;
  uint64_t rx_epoch_s;
  uint64_t msg_epoch_s;
  double latitude_deg;
  double longitude_deg;
  int32_t altitude_feet;
  uint32_t ground_track_deg;
  uint32_t ground_speed_kt;
  int32_t vertical_speed_fpm;
};
#define TERMINATOR12__OGN__POSITION_REPORT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&terminator12__ogn__position_report__descriptor) \
, (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0, 0, 0, 0 }


/* Terminator12__Ogn__PositionReport methods */
void   terminator12__ogn__position_report__init
                     (Terminator12__Ogn__PositionReport         *message);
size_t terminator12__ogn__position_report__get_packed_size
                     (const Terminator12__Ogn__PositionReport   *message);
size_t terminator12__ogn__position_report__pack
                     (const Terminator12__Ogn__PositionReport   *message,
                      uint8_t             *out);
size_t terminator12__ogn__position_report__pack_to_buffer
                     (const Terminator12__Ogn__PositionReport   *message,
                      ProtobufCBuffer     *buffer);
Terminator12__Ogn__PositionReport *
       terminator12__ogn__position_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   terminator12__ogn__position_report__free_unpacked
                     (Terminator12__Ogn__PositionReport *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Terminator12__Ogn__PositionReport_Closure)
                 (const Terminator12__Ogn__PositionReport *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor terminator12__ogn__position_report__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ogn_5fmessages_2eproto__INCLUDED */
