/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ogn_messages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ogn_messages.pb-c.h"
void   terminator12__ogn__position_report__init
                     (Terminator12__Ogn__PositionReport         *message)
{
  static const Terminator12__Ogn__PositionReport init_value = TERMINATOR12__OGN__POSITION_REPORT__INIT;
  *message = init_value;
}
size_t terminator12__ogn__position_report__get_packed_size
                     (const Terminator12__Ogn__PositionReport *message)
{
  assert(message->base.descriptor == &terminator12__ogn__position_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t terminator12__ogn__position_report__pack
                     (const Terminator12__Ogn__PositionReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &terminator12__ogn__position_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t terminator12__ogn__position_report__pack_to_buffer
                     (const Terminator12__Ogn__PositionReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &terminator12__ogn__position_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Terminator12__Ogn__PositionReport *
       terminator12__ogn__position_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Terminator12__Ogn__PositionReport *)
     protobuf_c_message_unpack (&terminator12__ogn__position_report__descriptor,
                                allocator, len, data);
}
void   terminator12__ogn__position_report__free_unpacked
                     (Terminator12__Ogn__PositionReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &terminator12__ogn__position_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor terminator12__ogn__position_report__field_descriptors[9] =
{
  {
    "callsign",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Terminator12__Ogn__PositionReport, callsign),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_epoch_s",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Terminator12__Ogn__PositionReport, rx_epoch_s),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg_epoch_s",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Terminator12__Ogn__PositionReport, msg_epoch_s),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "latitude_deg",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Terminator12__Ogn__PositionReport, latitude_deg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude_deg",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Terminator12__Ogn__PositionReport, longitude_deg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "altitude_feet",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Terminator12__Ogn__PositionReport, altitude_feet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ground_track_deg",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Terminator12__Ogn__PositionReport, ground_track_deg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ground_speed_kt",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Terminator12__Ogn__PositionReport, ground_speed_kt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vertical_speed_fpm",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Terminator12__Ogn__PositionReport, vertical_speed_fpm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned terminator12__ogn__position_report__field_indices_by_name[] = {
  5,   /* field[5] = altitude_feet */
  0,   /* field[0] = callsign */
  7,   /* field[7] = ground_speed_kt */
  6,   /* field[6] = ground_track_deg */
  3,   /* field[3] = latitude_deg */
  4,   /* field[4] = longitude_deg */
  2,   /* field[2] = msg_epoch_s */
  1,   /* field[1] = rx_epoch_s */
  8,   /* field[8] = vertical_speed_fpm */
};
static const ProtobufCIntRange terminator12__ogn__position_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor terminator12__ogn__position_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "terminator12.ogn.PositionReport",
  "PositionReport",
  "Terminator12__Ogn__PositionReport",
  "terminator12.ogn",
  sizeof(Terminator12__Ogn__PositionReport),
  9,
  terminator12__ogn__position_report__field_descriptors,
  terminator12__ogn__position_report__field_indices_by_name,
  1,  terminator12__ogn__position_report__number_ranges,
  (ProtobufCMessageInit) terminator12__ogn__position_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
